import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import CampaignTracking from "./components/CampaignTracking";
import LayoutWrapper from "./components/LayoutWrapper";
import { cairo, lays, mPlus1 } from "./fonts";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${lays.variable} ${mPlus1.variable} ${cairo.variable} h-full antialiased`}
    >
      <head>
        <CampaignTracking />
      </head>
      <body className="flex min-h-dvh flex-col">
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
